mysite/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.urls import path, re_path, include
from django.contrib import admin
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView


urlpatterns = [

    path('admin/',admin.site.urls),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('accounts/profile/', RedirectView.as_view(url='/'), name='go-to-django'),
    #re_path(r'', include(wagtail_urls)),
    path('',include('umasagar.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


umasagar/urls.py
from django.urls import path
from umasagar.views import index,SelectSupplierView,PurchaseCreateView,Boss1ApproveView,\
Boss2ApproveView,SaleView,LogApproveView,getprice,SaleBillView,edit_sale

app_name = 'umasagar'

urlpatterns = [

    path('', index, name = 'index'),
    path('customer/new', SelectSupplierView.as_view(), name='select-supplier'),
    path('customer/new/<str:pk>', PurchaseCreateView.as_view(), name='new-purchase'),
    path('sales/', SaleView.as_view(), name='sales-list'),
    path('b1approve/<int:pk>',Boss1ApproveView.as_view(),name = 'b1-approve'),
    path('b2approve/<int:pk>',Boss2ApproveView.as_view(),name = 'b2-approve'),
    path('logapprove/<int:pk>',LogApproveView.as_view(),name = 'log-approve'),
    path('getprice/',getprice,name = 'getprice'),
    path('sales/<billno>', SaleBillView.as_view(), name="sale-bill"),
    path('saleupdate/<name>/<billno>', edit_sale, name="edit-sale"),


    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>


  <title>{% block title %} {% endblock %}</title>
  
    
  <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- favicon.ico. Place these in the root directory. -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar.css' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/dialogbox.css' %}">


    {% block extrahead %}

    {% endblock %}


</head>

<body class="has-animations">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">UMASAGAR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'umasagar:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'umasagar:select-supplier' %}">New Sale</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'umasagar:sales-list' %}" >Sales List</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      &nbsp;&nbsp;&nbsp;&nbsp;
      {% if request.user.is_authenticated %}

      <span style="color:white">{{request.user.username}}</span>
      &nbsp;&nbsp;&nbsp;&nbsp;
          <a class="btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>

      {% else %}

          <a class="btn btn-outline-success" href="{% url 'login' %}">Login</a>

      {% endif %}
    </div>
  </div>
</nav>

<div class="container mt-5">
  {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}><b style="color: green">{{ message }}</b></li>
    {% endfor %}
</ul>
{% endif %}

{% block content %}

{% endblock %}

</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Index {% endblock %}

{% block extrahead %}

        <link rel="stylesheet" href="{% static 'css/production.css' %}">

        <!-- Web fonts -->
        <link href="https://fonts.googleapis.com/css?family=Space+Mono:400,700" rel="stylesheet">


{% endblock %}

{% block content %}


    <!-- Create outer border -->
    <div class="page-border">
    <div class="bg--white">

        <!-- Header -->
        <header class="align--center pt3 pb2">
            <div class="container">
                <h1 class="mb3 reveal-on-scroll is-revealing" title="7th Layer"><img src="{% static 'img/logo.png' %}" style="margin-left: -150px;" alt="Huddle"></h1>
                <h2 class="mb3 reveal-on-scroll is-revealing"> for everyone&nbsp;else.</h2>
                <p class="mb1">14 - 19 March 2022</p>
                <p>Stockholm, Sweden</p>
            </div>
        </header>

        <!-- Body -->
        <main>
            <div class="container">

                <!-- Info -->
                <section class="pt2 pb3">                    
                    <img class="mb3" src="{% static 'img/presentor.jpg' %}" alt="Huddle presentation">
                    <div class="grid-row">
                        <div class="grid-column span-one-third mt1 reveal-on-scroll is-revealing">
                            <img class="icon mb1" src="{% static 'img/bucket.svg' %}">
                            <p>Equidem soleo etiam quod uno Graeci, si aliter non possum idem&nbsp;pluribus.</p>
                        </div>
                        <div class="grid-column span-one-third mt1 reveal-on-scroll is-revealing">
                            <img class="icon mb1" src="{% static 'img/flask.svg' %}">
                            <p>Nonne videmus quanta perturbatio rerum omnium consequatur&nbsp;quanta.</p>
                        </div>
                        <div class="grid-column span-one-third mt1 reveal-on-scroll is-revealing">
                            <img class="icon mb1" src="{% static 'img/aircraft.svg' %}">
                            <p>Hoc enim constituto in philosophia constituta sunt omnia aliter&nbsp;possum.</p>
                        </div>
                    </div>
                     
                </section>

                <!-- Presenters -->
                <section class="pt3 pb3 align--center">
                    <h3 class="mb1">The talkers</h3>
                    <div class="grid-row">
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/woman1.jpg' %}" alt="Alyssa Long">
                            <p class="small">Alyssa Long</p>
                        </div>
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/man1.jpg' %}" alt="Jonathan Foster">
                            <p class="small">Jonathan Foster</p>
                        </div>
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/woman2.jpg' %}" alt="Kiara Taylor">
                            <p class="small">Kiara Taylor</p>
                        </div>
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/man2.jpg' %}" alt="Elijah Rhodes">
                            <p class="small">Elijah Rhodes</p>
                        </div>
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/woman3.jpg' %}" alt="Anita Gonzalez">
                            <p class="small">Anita Gonzalez</p>
                        </div>
                        <div class="grid-column span-2 mt2">
                            <img class="mb1" src="{% static 'img/man3.jpg' %}" alt="Adrian Sosa">
                            <p class="small">Adrian Sosa</p>
                        </div>
                    </div>
                </section>

                <!-- Sponsors -->
                <section class="pt3 pb3 align--center">
                    <h3 class="mb2">Some generous peeps</h3>
                    <img class="m1" src="{% static 'img/stripe.svg' %}" alt="Stripe" style="height:50px">
                    <img class="m1" src="{% static 'img/segment.svg' %}" alt="Segment" style="height:45px">
                    <img class="m1" src="{% static 'img/newrelic.svg' %}" alt="New Relic" style="height:35px">
                    <img class="m1" src="{% static 'img/drift.svg' %}" alt="Drift" style="height:50px">
                    <img class="m1" src="{% static 'img/zopim.svg' %}" alt="Zopim" style="height:50px">
                </section>

                <!-- Testimonials -->
                <section class="pt2 pb3">
                    <h3 class="align--center mb2">On the record</h3>
                    <div class="grid-row">
                        <div class="grid-column span-one-third mt1">
                            <blockquote class="blockquote">
                                <p>Equidem soleo etiam quod uno Graeci, si aliter non possum idem&nbsp;pluribus.</p>
                                <p>> <cite>Randy Johnson</cite></p>
                            </blockquote>
                        </div>
                        <div class="grid-column span-one-third mt1">
                            <blockquote class="blockquote">
                                <p>Nonne videmus quanta perturbatio rerum omnium consequatur&nbsp;quanta.</p>
                                <p>> <cite>Jill Carson</cite></p>
                            </blockquote>
                        </div>
                        <div class="grid-column span-one-third mt1">
                            <blockquote class="blockquote">
                                <p>Hoc enim constituto in philosophia constituta sunt omnia aliter&nbsp;possum.</p>
                                <p>> <cite>Chase Harrop</cite></p>
                            </blockquote>
                        </div>
                    </div>
                </section>

                <!-- CTA -->
                <section class="align--center pt3 pb3">
                    <p class="h3 mb2 reveal-on-scroll is-revealing">Pricing start at&nbsp;$950.</p>
                    <a href="#" class="btn btn--outline reveal-on-scroll is-revealing">Download Schedule</a>
                    <a href="#" class="btn btn--default reveal-on-scroll is-revealing">Get a Quote →</a>
                    <p class="small mt1 text--gray">Pricing available on 7th layer</p>
                </section>

            </div>
        </main>

        <!-- Footer -->
        <footer class="mt2 pb3 align--center">
            <ul class="no-bullets list--inline mb0">
                <li class="m1 block-on-mobile"><a href="https://www.twitter.com" class="link"><img class="icon" src="{% static 'img/twitter.svg' %}" alt="Twitter"> Twitter</a></li>
                <li class="m1 block-on-mobile"><a href="https://www.facebook.com" class="link"><img class="icon" src="{% static 'img/facebook.svg' %}" alt="Facebook"> Facebook</a></li>
                <li class="m1 block-on-mobile"><a href="https://www.instagram.com" class="link"><img class="icon" src="{% static 'img/instagram.svg' %}" alt="Instagram"> Instagram</a></li>
                <li class="m1 block-on-mobile"><a href="https://www.youtube.com" class="link"><img class="icon" src="{% static 'img/youtube.svg' %}" alt="YouTube"> YouTube</a></li>
            </ul>
            <p class="mt1 small text--gray">Design by <a href="#" class="link">7th Layer</a>.</p>
        </footer>

    </div>
    </div>



    <!-- Scroll reveal -->
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>

    <!-- The compiled JavaScript file -->
    <script src="{% static 'js/production.js' %}"></script>




{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login </title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'login/css/login.css' %}">

  <script src="https://kit.fontawesome.com/05c146b6c7.js" crossorigin="anonymous"></script>
</head>
<body>
  <main>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 login-section-wrapper">
          <div class="brand-wrapper">
            <img src="{% static 'img/aircraft.svg' %}" alt="logo" class="logo">
          </div>
          <div class="login-wrapper my-auto">
            <h1 class="login-title">Log in</h1>
            <form method="POST" autocomplete="off">
              {% csrf_token %}
              <div class="form-group">
                {% if form.errors %}
                    <p class="label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}
                <label for="email">Username</label>
                <input type="text" name="username" id="id_username" autofocus="" autocapitalize="none" maxlength="150" class="form-control" placeholder="John Doe">
              </div>
              <div class="form-group mb-4">
                <label for="password">Password</label>
                <input type="password" name="password" id="id_password" class="form-control" placeholder="Password Here">
              </div>
              <input name="login" id="login" class="btn btn-block login-btn" type="submit" value="Login">
            </form>
            <a href="{% url 'umasagar:index' %}" class="forgot-password-link">Go Back?</a>
            <i class="fas fa-chevron-circle-left"></i>
          </div>
        </div>
        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img src="{% static 'login/images/login.jpg' %}" alt="login image" class="login-img">
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

templates/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  
{% endblock %}