mysite/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.urls import path, re_path, include
from django.contrib import admin
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView


urlpatterns = [

    path('admin/',admin.site.urls),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('accounts/profile/', RedirectView.as_view(url='/'), name='go-to-django'),
    #re_path(r'', include(wagtail_urls)),
    path('',include('umasagar.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


umasagar/urls.py
from django.urls import path
from umasagar.views import index,SelectSupplierView,PurchaseCreateView,Boss1ApproveView,\
Boss2ApproveView,SaleView,LogApproveView,getprice,SaleBillView,edit_sale

app_name = 'umasagar'

urlpatterns = [

    path('', index, name = 'index'),
    path('customer/new', SelectSupplierView.as_view(), name='select-supplier'),
    path('customer/new/<str:pk>', PurchaseCreateView.as_view(), name='new-purchase'),
    path('sales/', SaleView.as_view(), name='sales-list'),
    path('b1approve/<int:pk>',Boss1ApproveView.as_view(),name = 'b1-approve'),
    path('b2approve/<int:pk>',Boss2ApproveView.as_view(),name = 'b2-approve'),
    path('logapprove/<int:pk>',LogApproveView.as_view(),name = 'log-approve'),
    path('getprice/',getprice,name = 'getprice'),
    path('sales/<billno>', SaleBillView.as_view(), name="sale-bill"),
    path('saleupdate/<name>/<billno>', edit_sale, name="edit-sale"),


    
]

umasagar/models.py
from django.db import models
from authentication.models import MyUser,Company
import uuid
from umasagar.validators import validate_pk
from datetime import datetime
import uuid
from django.db.models import Sum
# Create your models here.

class TimeStamp(models.Model):
    time = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(MyUser,on_delete = models.CASCADE)

    class Meta:
        abstract = True

class CropGroup(models.Model):
	crop_group = models.CharField(max_length = 100)

	def __str__(self):
		return self.crop_group

class CropCode(models.Model):
	crop_code = models.CharField(max_length = 100)

	def __str__(self):
		return self.crop_code

class CropCategory(models.Model):
	crop_category = models.CharField(max_length = 100)

	def __str__(self):
		return self.crop_category

	class Meta:
		verbose_name = "Category"
		verbose_name_plural = "Categories"

class Stage(models.Model):
	stage = models.CharField(max_length = 100)

	def __str__(self):
		return self.stage

class VarietyCode(models.Model):
	variety_code = models.CharField(max_length = 100,unique = True,primary_key = True,validators=[validate_pk])

	def __str__(self):
		return self.variety_code

class UOM(models.Model):
	uom = models.CharField(max_length = 100)

	def __str__(self):
		return self.uom

class Product(models.Model):
	company = models.ForeignKey(Company, on_delete = models.CASCADE)
	crop_group = models.ForeignKey(CropGroup, on_delete = models.CASCADE)
	crop_code = models.ForeignKey(CropCode, on_delete = models.CASCADE)
	crop_category = models.ForeignKey(CropCategory, on_delete = models.CASCADE)
	stage = models.ForeignKey(Stage, on_delete = models.CASCADE)
	variety_code = models.OneToOneField(VarietyCode, on_delete = models.CASCADE,primary_key = True)
	uom = models.ForeignKey(UOM, on_delete = models.CASCADE)
	pack_size = models.CharField(max_length = 100)
	price = models.DecimalField(max_digits = 15,decimal_places = 2)

	def __str__(self):
		return str(self.variety_code)



class SaleBill(TimeStamp):
    billno = models.AutoField(primary_key=True)
    order = models.UUIDField(default=uuid.uuid4, editable=False)
    time = models.DateTimeField(auto_now=True)
    dealer = models.ForeignKey(MyUser, on_delete = models.SET_NULL, related_name='saledealer',null = True,verbose_name = 'select user')
    name = models.CharField(max_length=150,blank = True,null = True)
    phone = models.CharField(max_length=13,blank = True,null = True)
    address = models.TextField(blank = True,null = True)
    email = models.EmailField(max_length=254,blank = True,null = True)
    lrno = models.CharField(max_length = 254,blank = True,null = True,verbose_name = 'LR No.')
    vehicleno = models.CharField(max_length = 254,blank = True,null = True,verbose_name = 'Vehicle No.')
    #gstin = models.CharField(max_length=15)
    s1approve = models.BooleanField(default = False,verbose_name = 'Approve')
    s2approve = models.BooleanField(default = False,verbose_name = 'Approve')
    logapprove = models.BooleanField(default = False,verbose_name = 'Approve')


    def __str__(self):
        return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return SaleItem.objects.filter(billno=self)

    def get_total_price(self):
        saleitems = SaleItem.objects.filter(billno=self)
        total = 0
        for item in saleitems:
            total += item.totalprice
        return total



#contains the sale stocks made
class SaleItem(models.Model):
    billno = models.ForeignKey(SaleBill, on_delete = models.CASCADE, related_name='salebillno')
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)
    despatched = models.IntegerField(default = 0)
    remaining = models.IntegerField(default=0)
    perprice = models.FloatField(default=1)
    totalprice = models.FloatField(default=1)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno) + ", Item = " + str(self.product.variety_code)



class SaleBillDetails(TimeStamp):
    user = models.ForeignKey(MyUser,on_delete = models.CASCADE,blank = True,null=True)
    billno = models.ForeignKey(SaleBill, on_delete = models.CASCADE, related_name='saledetailsbillno')
    
    eway = models.CharField(max_length=50, blank=True, null=True)    
    veh = models.CharField(max_length=50, blank=True, null=True)
    destination = models.TextField(blank=True, null=True)
    po = models.CharField(max_length=50, blank=True, null=True)
    transporter = models.CharField(max_length=50, default = 'First Last')
    cgst = models.CharField(max_length=50, blank=True, null=True)
    sgst = models.CharField(max_length=50, blank=True, null=True)
    igst = models.CharField(max_length=50, blank=True, null=True)
    cess = models.CharField(max_length=50, blank=True, null=True)
    tcs = models.BooleanField(default = False)
    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
	    return "Bill no: " + str(self.billno.billno)

umasagar/views.py
from django.shortcuts import render,redirect, get_object_or_404, reverse
from django.http import HttpResponse,JsonResponse
from django.views.generic import (
    View, 
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.forms.models import inlineformset_factory
from umasagar.models import Product,SaleBillDetails,SaleBill,SaleItem
from authentication.models import MyUser
from umasagar.forms import SaleItemFormset,SelectDealerForm,SaleForm,\
Boss1ApproveForm,Boss2ApproveForm,LogApproveForm,SaleItemForm,dSaleItemForm
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from datetime import datetime
from django.db.models import Sum

# Create your views here.
def index(request):
	return render(request,'index.html')



# used to select the customer
class SelectSupplierView(LoginRequiredMixin,View):
    form_class = SelectDealerForm
    template_name = 'select_customer.html'

    def get(self, request, *args, **kwargs):                                    # loads the form page
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):                                   # gets selected supplier and redirects to 'PurchaseCreateView' class
        form = self.form_class(request.POST)
        print(form)
        print(request.POST)
        if form.is_valid():
            supplierid = request.POST.get("dealer")
            supplier = get_object_or_404(MyUser, username=supplierid)
            print(supplier.pk)
            return redirect('umasagar:new-purchase', supplier.pk)
        return render(request, self.template_name, {'form': form})


# used to generate a bill object and save items
class PurchaseCreateView(LoginRequiredMixin,View):                                                 
    template_name = 'new_sale.html'

    def get(self, request, pk):
        formset = SaleItemFormset(request.GET or None)                      # renders an empty formset
        supplierobj = get_object_or_404(MyUser, pk=pk)                        # gets the supplier object
        context = {
            'formset'   : formset,
            'supplier'  : supplierobj,
        }                                                                       # sends the supplier and formset as context
        return render(request, self.template_name, context)

    def post(self, request, pk):
        formset = SaleItemFormset(request.POST)                             # recieves a post method for the formset
        supplierobj = get_object_or_404(MyUser, pk=pk)
        #                       # gets the supplier object
        data = {'name':supplierobj.username,'phone':supplierobj.mobile,'email':supplierobj.email }
        form = SaleForm(data)
        
            
        if form.is_valid() and formset.is_valid():
            # saves bill
            billobj = form.save(commit=False)
            billobj.dealer = supplierobj
            billobj.user = request.user
            billobj.address = request.user.address
            billobj.save()     
            # create bill details object
            billdetailsobj = SaleBillDetails(billno=billobj)
            billdetailsobj.save()
            for form in formset:                                  # for loop to save each individual form as its own object
                print(form)
                # false saves the item and links bill to the item

                billitem = form.save(commit=False)
                billitem.billno = billobj                                       # links the bill object to the items
                    
                # calculates the total price
                billitem.despatched = billitem.quantity
                billitem.totalprice = billitem.perprice * billitem.quantity
                   
                # saves bill item
                try:
                    billitem.save()
                except:
                    messages.info(request, 'Select any Product')
                    return redirect('umasagar:sales-list')

                if settings.USE_EMAIL:
                    #current_site = get_current_site(request)
                    send_mail(
    'Waiting for Approval !',
    "Hi, {} 's sale bill {} is waiting for your approval , Visit {} .".format(supplierobj,billobj,\
        request.build_absolute_uri(reverse('umasagar:b1-approve', kwargs={'pk':billobj.pk})) ),
    settings.DEFAULT_FROM_EMAIL,
    [request.user.officer.email,],
    fail_silently=False,
)
            messages.success(request, 'Approval is Sent Successfully.')
            
        return redirect('umasagar:sales-list')

class Boss1ApproveView(LoginRequiredMixin,View):
    form_class = Boss1ApproveForm
    template_name = 'b1_approve.html'

    def get(self, request, *args, **kwargs):                                    # loads the form page
        sale = SaleBill.objects.get(pk = kwargs['pk'])
        form = self.form_class
        return render(request, self.template_name, {'form': form,'sale':sale})

    def post(self, request, *args, **kwargs):                                   # gets selected supplier and redirects to 'PurchaseCreateView' class
        form = self.form_class(request.POST)
        if form.is_valid():
            approve = request.POST.get("s1approve")
            result = True if approve == 'on' else False
            salebill = get_object_or_404(SaleBill, pk = kwargs['pk'])
            salebill.s1approve = result
            salebill.save()
            if settings.USE_EMAIL and result:
                    #current_site = get_current_site(request)
                    send_mail(
    'Waiting for Approval !',
    "Hi, {} 's sale bill {} is waiting for your approval , Visit {} .".format(salebill.dealer,salebill.billno,\
        request.build_absolute_uri(reverse('umasagar:b2-approve', kwargs={'pk':salebill.pk})) ),
    settings.DEFAULT_FROM_EMAIL,
    [request.user.officer.email,],
    fail_silently=False,
)
                    messages.success(request, 'Approval is Sent Successfully.')
            return redirect('umasagar:sales-list')
        return render(request, self.template_name, {'form': form})

class Boss2ApproveView(LoginRequiredMixin,View):
    form_class = Boss2ApproveForm
    template_name = 'b2_approve.html'

    def get(self, request, *args, **kwargs):                                    # loads the form page
        sale = SaleBill.objects.get(pk = kwargs['pk'],s1approve = True)
        form = self.form_class
        return render(request, self.template_name, {'form': form,'sale':sale})

    def post(self, request, *args, **kwargs):                                   # gets selected supplier and redirects to 'PurchaseCreateView' class
        form = self.form_class(request.POST)
        if form.is_valid():
            approve = request.POST.get("s2approve")
            result = True if approve == 'on' else False
            salebill = get_object_or_404(SaleBill, pk = kwargs['pk'])
            salebill.s2approve = result
            salebill.save()
            saleitems = SaleItem.objects.filter(billno = salebill)
            for i in saleitems:
                i.despatched = i.quantity
                i.save()
            if settings.USE_EMAIL and result:
                    #current_site = get_current_site(request)
                    send_mail(
    'Waiting for Approval !',
    "Hi, {} 's sale bill {} is waiting for your approval , Visit {} .".format(salebill.dealer,salebill.billno,\
        request.build_absolute_uri(reverse('umasagar:b2-approve', kwargs={'pk':salebill.pk})) ),
    settings.DEFAULT_FROM_EMAIL,
    [request.user.officer.email,],
    fail_silently=False,
)
                    messages.success(request, 'Approval is Sent Successfully.')
            return redirect('umasagar:sales-list')
        return render(request, self.template_name, {'form': form})


class LogApproveView(LoginRequiredMixin,View):
    form_class = LogApproveForm
    template_name = 'log_approve.html'


    def get(self, request, *args, **kwargs):                                    # loads the form page
        pk = kwargs['pk']
        sale = SaleBill.objects.get(pk = pk,s1approve = True,s2approve = True)
        form = self.form_class
        salebill = SaleBill.objects.get(billno = pk)
        supplierobj = get_object_or_404(MyUser, pk=salebill.dealer)
        no = SaleItem.objects.filter(billno=pk).count()
        SaleItemFormSet = inlineformset_factory(SaleBill, SaleItem, form=dSaleItemForm, fields=('quantity','despatched','remaining', 'perprice', 'product'),extra = no//2 - 1 if no//2 > 1 else 0)
        formset = SaleItemFormSet(instance=salebill)

        return render(request, self.template_name, {'form': form,'sale':sale,'formset':formset,'supplier':supplierobj})

    def post(self, request, *args, **kwargs):
        pk = kwargs['pk']
        salebill = SaleBill.objects.get(billno = pk)
        no = SaleItem.objects.filter(billno=pk).count()
        SaleItemFormSet = inlineformset_factory(SaleBill, SaleItem, form=dSaleItemForm, fields=('quantity','despatched','remaining', 'perprice', 'product'),extra = no//2 - 1 if no//2 > 1 else 0)
        formset = SaleItemFormSet(request.POST, instance=salebill)
        
        supplierobj = salebill.dealer
        #                       # gets the supplier object
        data = {'name':supplierobj.username,'phone':supplierobj.mobile,'email':supplierobj.email }
        saleform = SaleForm(data)
        
            
        if saleform.is_valid() and formset.is_valid():
            # saves bill

umasagar/templates/b1_approve.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}



{% if request.user.usertype.usertype == "b1" %}

<div class="mt-5">

	<div>
        <table class="table table-css">
		<thead class="thead-inverse align-middle">
            <tr>
                <th width="10%">Bill No</th>
                <th width="15%">Customer</th>
                <th width="15%">Product Sold</th>
                <th width="10%">Quantity Sold</th>
                <th width="10%">Total Sold Price</th>
                <th width="15%">Sale Date</th>
                <th width="25%">Others</th>
            </tr>
        </thead>
		<tbody><tr>
		<td class="align-middle"> <h3>{{ sale.billno }}</h3> </td>
                <td class=""> {{ sale.name }} <br> <small style="color: #909494">Ph No : {{ sale.phone }}</small> </td>
                <td class="align-middle">{% for item in sale.get_items_list %} {{ item.product.variety_code }} - {{item.product.uom}} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in sale.get_items_list %} {{ item.quantity }} <br> {% endfor %}</td>     
                <td class="align-middle">{{ sale.get_total_price }}</td>
                <td class="align-middle">{{ sale.time.date }}</td>
                <td></td>
        </tr></tbody>
        </table>
	</div>

<form class="form-control" action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-outline-success" type="submit" value="Submit">
</form>

</div>

{% else %}

No Permissions

{% endif %}

{% endblock %}


umasagar/templates/edit_sale.html
{% extends "base.html" %}
{% load static %}
{% load multi %}


{% block title %} New Sale {% endblock title %}


{% block content %}


    <div style="color:#402657; font-style: bold; font-size: 1.5rem; border-bottom: 1px solid white;">New Sale</div>
    
        <br>

        <div class="panel panel-default">
            <div style="color:#402657; font-style: bold; font-size: 1.2rem; border-bottom: 1px solid white;">Customer Details</div>
            <br>
            <div class="panel-body">


                    
                <div class="form-group col-md-6">
                    <label for="id_name" class="panel-body-text">Customer Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{ supplier.username }}" disabled>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="id_phone" class="panel-body-text">Phone No:</label>
                        <input type="text" class="form-control textinput" id="id_phone" value="{{ supplier.mobile }}" disabled>
                    </div>
                    <div class="col-md-6">
                        <label for="id_email" class="panel-body-text">Email:</label>
                        <input type="email" class="form-control textinput" id="id_gstin" value="{{ supplier.email }}" disabled>
                    </div>
                </div>

            </div>
        </div>

        <br>

        <form method="post" class="panel panel-default" autocomplete="off">
            
            {% csrf_token %}
            {{ formset.management_form }}

            <div class="panel-heading panel-heading-text">Product Details</div>
            
                <div id="stockitem"> 
                    <div class="panel-body">
                    {% for form in formset %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}


                        <div class="row form-row">
                            <div class="form-group col-md-4">
                                {{ form.product.errors }}
                                <label class="panel-body-text">Product:</label>
                                <input type="text" list="productlist" placeholder="Select Product" class="form-select setprice stock" style="width: 300px;" name="salebillno-{{forloop.counter0}}-product" id="id_salebillno-{{forloop.counter0}}-product" value="{{form.initial.product}}" required >

                                
                                
                                

    

                                     <datalist id="productlist">

                                     {% for i,j in form.product.field.choices %}

                                     <option value="{{i}}">{{j}}</option>

                                     {% endfor %}

                                     </datalist>

                            
                                


        

                            </div>

                            

                            <div class="form-group col-md-3">
                                <label class="panel-body-text">Price per item:</label>
                                {{ form.perprice }}
                            </div>
                            <div class="form-group col-md-1">
                                {{ form.quantity.errors }}
                                <label class="panel-body-text">Quantity:</label>
                                {{ form.quantity }}
                            </div>
                            <div class="form-group col-md-3">
                                <label class="panel-body-text">Price:</label>    
                                <input type="text" class="textinput form-control totalprice" value="{% multi form.initial.perprice form.initial.quantity %}" disabled required>
                            </div>
                            <div class="form-group col-md-1">
                                <label class="panel-body-text" style="color: #000"></label>
                                <button class="form-control btn btn-danger remove-form-row">- Delete</button>
                            </div>
                        </div> 

                            

                            <script type="text/javascript">

                                // On Stock input using scanner or manually typing 
                                $(document).on('input', '.stock', function (e) {
                                    e.preventDefault();
                                    //gets the values
                                    var element = $(this);
                                    var product = element.parents('.form-row').find('.stock').val();

                                    $.ajax({
                                        url : "{% url 'umasagar:getprice' %}",
                                        data : { 'product' : product },
                                        success : function(data){
                                            var id_getprice = $('.price:last').attr("id");
                                            var id_quantity = $('.quantity:last').attr("id");
                                            document.getElementById(`${id_getprice}`).value = data.price;
                                            document.getElementById(`${id_quantity}`).value = 1;
                                            var id_name = $('.stock:last').attr("id");
                                            // document.getElementById(`${id_name}`).value = data.name;
                                            var quantity = element.parents('.form-row').find('.quantity').val();
                                            var perprice = element.parents('.form-row').find('.price').val();
                                            //calculates the total
                                            var tprice = quantity * perprice;
                                            //sets it to field
                                            element.parents('.form-row').find('.totalprice').val(tprice);
                                            // generateTotal();
                                            // cloneMore('.form-row:last', 'form');
                                        }
                                    })


                                });
                                

                                $(document).on('input', '.quantity', function (e) {
                                    e.preventDefault();
                                    //gets the values
                                    var element = $(this);
                                    var quantity = element.parents('.form-row').find('.quantity').val();
                                    var perprice = element.parents('.form-row').find('.price').val();
                                    var tprice = quantity * perprice;
                                    element.parents('.form-row').find('.totalprice').val(tprice);


                                });


                            </script>


                    {% endfor %}
                        <div class = "mt-3" style="text-align: right;">                    
                            <a href="#" class="add-form-row btn btn-success">+ Add More</a>
                        </div>
                    </div>
                </div>


            <br>

            <div class="align-middle">
                <button type="submit" class="btn ghost-green">Update Sales</button>
                <a href="{% url 'umasagar:index' %}" class="btn ghost-button">Go Back</a>
                <a href="{% url 'umasagar:index' %}" class="btn ghost-button">Cancel</a>
            </div>
            
        </form>

    </div>

    <!-- Custom JS to add and remove item forms -->

    <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
    <script type="text/javascript">
        
        //creates custom alert object
        var custom_alert = new custom_alert();

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        
        //stores the total no of item forms
        var total = 1;

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            //var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
                var name = $(this).attr('name')
                if(name) {
                    name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                }
            });
            newElement.find('label').each(function() {
                var forValue = $(this).attr('for');
                if (forValue) {
                forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            return false;
        }
        
        function deleteForm(prefix, btn) {
            //var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
                total--;
            } else {
                custom_alert.render("Field cannot be deleted");
            }
            return false;
        }
        
        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        
        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


        //updates the total price by multiplying 'price per item' and 'quantity' 
        $(document).on('change', '.setprice', function(e){
            e.preventDefault();
            //gets the values
            var element = $(this);
            var quantity = element.parents('.form-row').find('.quantity').val();
            var perprice = element.parents('.form-row').find('.price').val();
            //calculates the total
            var tprice = quantity * perprice;
            //sets it to field
            element.parents('.form-row').find('.totalprice').val(tprice);
            return false;
        });

    </script>



{% endblock content %}

umasagar/templates/select_customer.html
{% extends "base.html" %}


{% block title %} New Sale {% endblock title %}


{% block content %}



{% if request.user.usertype.usertype == 'user' %}





<span>No Permissions</span>


{% else %}


    <div style="color:#402657; font-style: bold; font-size: 1.5rem; border-bottom: 1px solid white;">New Sale</div> 
    
    <br>
    
    <form method="post">

        {% csrf_token %}


        <input type="text" list="userlist" placeholder="Select User" class="form-select" style="width: 300px;" name="dealer" id="id_dealer" autocomplete="off">

    

        <datalist id="userlist">

        {% for i,j in form.dealer.field.choices %}

        <option value="{{i}}">{{j}}</option>

        {% endfor %}

        </datalist>

        
        
        <!-- {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %} -->

        <br>
        <div class="align-middle">
            <button type="submit" class="btn ghost-green">Next</button>
            <a href="#" class="btn ghost-button">Cancel</a>
        </div>
        
    </form>




{% endif %}

{% endblock content %}
